name: Build & Release
on:
  push:
    tags: [ 'v*' ]
jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Build DMG
        run: npm run electron:build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.dmg
            release/*.blockmap
            release/latest-mac.yml
          generate_release_notes: true
          make_latest: true
